version: '3.8'

services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "devopsenv:1.0"
    image: devopsenv:1.0
    stdin_open: true 
    tty: true
    container_name: devops
    # environment:
    # networks:
    volumes:
      - ./workspace:/root/workspace
      - ./tmp:/tmp
    # ports: